In [2]:
import cv2
import numpy as np

In [3]:
def display(img):
    cv2.imshow('Image', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [14]:
image = cv2.imread('./Data/Test/test2.png')

In [17]:
point1 = None
point2 = None
cropped = None

def kMeans(clusters, img):
    points = img.reshape((-1,3)).astype(np.float32)
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
    _,labels,centers=cv2.kmeans(points,clusters,None,criteria,20,cv2.KMEANS_RANDOM_CENTERS)
    print(centers)
    labels = labels.reshape((img.shape[0], img.shape[1]))
    print(labels)
    
    for i in range(clusters):
        output = img.copy()
        output[labels!=i]=np.uint8([0,0,0])
        title = "Image " + str(i +1)
        cv2.imshow(title, output)

    
    
    

def crop(event, x,y,flag,param):
    global point1, point2, cropped
    
    if event == cv2.EVENT_LBUTTONDOWN:
        if point1 is None:
            point1 = (x,y)
        elif point2 is None:
            point2 = (x,y)
            
            minY = min(point1[1], point2[1])
            maxY = max(point1[1], point2[1])
            if minY != maxY:
                cropped= image[minY:maxY, :] 
            point1= None
            point2= None
        
    
cv2.namedWindow('Image') 
cv2.setMouseCallback("Image", crop)
try:
    while(1):  
        cv2.imshow('Image',image)  
        if cropped is not None:
            croppedHSV = cv2.cvtColor(cropped, cv2.COLOR_BGR2HSV)
            cv2.imshow('Crop', cropped)
           
            width = int(cropped.shape[1]/3)
            square1 = cropped[:, :width]
            square2 = cropped[:, width: width*2]
            square3 = cropped[:, width*2: ]
            kMeans(3, square1)
            kMeans(3, square2)
            kMeans(3, square3)

#             cv2.imshow('Square 1',square1)  
#             cv2.imshow('Square 2',square2)  
#             cv2.imshow('Sqaure 3',square3) 
            cropped= None
        if cv2.waitKey(1) & 0xFF == 27:  
            break 
except Exception as e:
    print(e)

cv2.destroyAllWindows()


[[153.26678  159.84543  154.73938 ]
 [ 41.37576  156.3977   193.8001  ]
 [108.83232  109.70987   95.778496]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 2 2 2]
 [0 0 0 ... 2 2 2]
 [0 0 0 ... 2 2 2]]
[[112.05186  102.956856  88.158615]
 [186.17685  181.8822   173.31229 ]
 [155.53557  149.67862  134.77106 ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [2 1 1 ... 1 1 1]
 ...
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]]
[[196.0421   197.29306  195.67632 ]
 [166.62993  167.43768  166.0226  ]
 [ 41.802437  32.144512  77.78474 ]]
[[1 1 1 ... 1 1 2]
 [1 1 1 ... 1 1 2]
 [1 1 1 ... 1 1 2]
 ...
 [1 1 1 ... 2 2 2]
 [1 1 1 ... 2 2 2]
 [1 1 1 ... 2 2 2]]


In [122]:
##### #             width = int(cropped.shape[1]/3)
#             square1 = cropped[:, :width]
#             square2 = cropped[:, width: width*2]
#             square3 = cropped[:, width*2: ]
#             cv2.imshow('Square 1',square1)  
#             cv2.imshow('Square 2',square2)  
#             cv2.imshow('Sqaure 3',square3) 
[[135.17746  133.47664  128.10077 ]
 [ 31.805359  21.211466  58.292572]
 [174.25406  172.13939  167.96521 ]]

[[ 23.154455 199.46794  198.38054 ]
 [103.16753   32.517647 154.78535 ]
 [ 29.758947  24.204458 143.45663 ]]23